### ISSUE TITLE
🌞 [Other]: ArgumentCompleter

### ISSUE THREAD

**Issue by webalexeu** [PSModule/Build-PSModule#55]
### Description

Hello,

I'm trying to use an ArgumentCompleter in my module but I don't know where to define it properly to be build correclty

Thanks for your support,
Alexandre

**Comment by MariusStorhaug** [comment]
Hey, and thank you for using the framework!

I only have an example of this in the Font module, where I register a completer in the same file, but the function could be located in the private folder. The private functions are loaded first, then public functions (which will be exported).

**Comment by webalexeu** [comment]
Thank you for your quick answer

I finally use the init folder as my argument completer is used by multiple cmdlets but thanks for the exemple

I've another question, I was thinking that variable (included in data folder) will be declared with 

> `-Scope Script` 

but that's not. I was guessing it will be due to this document note

> Adds data loader automation that loads files from the data folder as variables in the module scope, if it exists. The variables are available using the ´$script:´ syntax.

**Comment by MariusStorhaug** [comment]
Just wanted to let you know before i close this issue for now: 
- Data is now loaded two ways, the data folder and the variables folder. The variables folder must contain a folder for private and public, the public ones will be exported, the private will not. Both are available in the `Script` scope for the module. Example of this can be seen in both [Context](github.com/PSModule/Context) and [GitHub](github.com/PSModule/GitHub).

Again, thank you for using the framework. Nice to see it provides value for someone other than myself :)

**Comment by webalexeu** [comment]
> Just wanted to let you know before i close this issue for now:
> 
> * Data is now loaded two ways, the data folder and the variables folder. The variables folder must contain a folder for private and public, the public ones will be exported, the private will not. Both are available in the `Script` scope for the module. Example of this can be seen in both [Context](github.com/PSModule/Context) and [GitHub](github.com/PSModule/GitHub).
> 
> Again, thank you for using the framework. Nice to see it provides value for someone other than myself :)

@MariusStorhaug tested and working as expected

Thank you again
